#!/usr/bin/env bash

# Directory in which to copy `bazel-bin`.
#
# Needs to be consistent with the `output_path` in `hello_transparent_release.toml`.
readonly OUTPUT_DIR='out'

bazel build //:HelloTransparentRelease 

# Because bazel builds in the home directory of root, copy bazel-bin to the 
# directory `out` shared with the host.
cp -Lr bazel-bin ${OUTPUT_DIR} 
