#!/usr/bin/env bash

# Build the builder Docker Image for hello-transparent-release binary.
readonly DOCKER_IMAGE_NAME='gcr.io/oak-ci/hello-transparent-release:latest'

docker build \
  --tag="${DOCKER_IMAGE_NAME}" \
 .
